### ISSUE TITLE
Unregistered functions

### ISSUE THREAD

**Issue by zgleicher** [ColumbiaJS/hw3#3]
For the test, "shouldn\'t treat the parameters in nested functions as dependencies" in DI.spec.js simple, parameters 'app' and 'login' have not been registered. 'login' does not even exist. Should it be Auth and User instead?

**Comment by levbrie** [comment]
@zgleicher Yes, it probably should be Auth and User but your tests should pass regardless.  I believe at some point I renamed app and and long to Auth and User, but ended up neglecting this test because it passes anyway, since this particular test is testing how many arguments your inject method has parsed and making sure it doesn't parse nested functions, rather than actually making use of any of those nested injected functions as it does in other tests.  Good catch!

**Comment by levbrie** [comment]
Also, please make sure to ask this in js-course so everyone sees it and just apply the label hw3 to it.  I'll do that now.
